<?php
/**
 * @file
 * Code for the GSB Feature Featured Program FPP feature.
 */

include_once 'gsb_feature_featured_program_fpp.features.inc';
/**
 * @file
 * Code for the GSB Feature Featured Program FPP feature.
 */

 /**
 * Implements hook_entity_alter().
 */
function gsb_feature_featured_program_fpp_entity_info_alter(&$entity_info) {

  $entity_info['fieldable_panels_pane']['bundles']['featured_program'] = array(
    'label' => t('Featured Program'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/featured-program',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function gsb_feature_featured_program_fpp_form_alter(&$form, &$form_state, $form_id) {
  if (($form_id == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form' || $form_id == 'fieldable_panels_panes_entity_edit_form')
     && $form_state['entity']->bundle == 'featured_program') {
       $form['title']['#access'] = FALSE;
       $form['link']['#access'] = FALSE;
  }
}

/**
 * Implements hook_preprocess_HOOK() for fieldable-panels-pane.tpl.php.
 */
function gsb_feature_featured_program_fpp_preprocess_fieldable_panels_pane(&$variables) {
  if ($variables['elements']['#bundle'] != 'featured_program') {
    return;
  }

  // Add classes based on the position and color chosen.
  try {
    $wrapper = entity_metadata_wrapper('fieldable_panels_pane', $variables['elements']['#element']);
    $variables['classes_array'][] = 'featured-program-color-' . $wrapper->field_color_overlay->value();
  }
  catch (EntityMetadataWrapperException $e) {
    // If the fields are ever missing/renamed, Entity API will throw an
    // exception instead of using watchdog.
    watchdog('gsb_feature_featured_program_fpp', 'In @function on line @line: "@message"', array('@function' => __FUNCTION__, '@line' => __LINE__, '@message' => $e->getMessage()), WATCHDOG_ERROR);
  }
}
